### PR TITLE
Fix combinational sensitivity excessive pessimism, fix #233

### LINKED ISSUE #233: `Combinational` sensitivity detection is excessively pessimistic
### Describe the bug

The current implementation that searches for expanded sensitivity lists in `Combinational` will not look "inside" other `Module`s along the path from its outputs to inputs.  If a `Sequential` is inside of another `Module` along the path, it will skip over it assuming that any input may have a combinational path to any output.  This is excessively pessimistic, and can lead to detection of non-existent combinational loops in `Logic` reentrance checking.

### To Reproduce

Connections like shown below will reproduce this issue:
```
  ______________________
  | Module             |
--|--- [Sequential] ---|--
| |____________________| |
|                        |
-----[Combinational]------
```

If the combinational in the diagram is also responsible for driving some other input to the module, it can cause a false combinational loop detection.

### Expected behavior

No invalid detection of combinational loops.

### Actual behavior

X generation due to reentrance detection in `Logic.put`

### Additional: Dart SDK info

_No response_

### Additional: pubspec.yaml

_No response_

### Additional: Context

_No response_

### PR DESCRIPTION
**Pull request by mkorbel1**
## Description & Motivation

Issue #233 finds that searches for `Combinational` sensitivity lists, it is excessively pessimistic in that sometimes there aren't really any combinational paths, but it assumes that there may be.  This can cause an issue where a false combinational loop is detected, causing incorrect X-generation.

This PR fixes the bug by calculating more detailed combinational paths for `Module`s at `build` time.  This information can be leveraged by `Combinational` to understand more accurately where combinational paths may exist.  Results are cached to avoid repeated calculations when multiple `Combinational`s search through similar paths of potential sensitivities.  All `Module`s with custom functionality must explicitly define any combinational paths from all inputs to applicable outputs or else `Combinational` will be unable to properly determine an accurate sensitivity list.  A new `FullyCombinational` mixin is included in this PR to automatically add all input/output combinations as potential combinational paths, since that's a common case for many small custom gates.

Additionally,
- Added `RohdException` base type for all ROHD exceptions, making it easier to handle ROHD-related exceptions
- Added new `ModuleNotBuiltException`, used in multiple places in `Module`

## Related Issue(s)

Fix #233 

## Testing

- Added a new test that had reproduced the original issue without this fix.
- Existing tests cover scenarios where non-trivial sensitivities exist.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible?  If yes, how so?

Other custom functionality modules defined outside of the ROHD framework which had previously benefited from assumption of the behavior of `FullyCombinational` will now be treated as the complete opposite (no combinational paths).  This could mean `Combinational`s would now be missing sensitivities that previously existed.  If those sensitivities were true, then existing simulations in ROHD might now have incorrect behavior.  This is likely rare, and since this is really a bug fix it doesn't quite feel like it's breaking backwards-compatibility.

## Documentation

> Does the change require any updates to documentation?  If so, where?  Are they included?

Doc comments updated/included

### CODE REVIEW

File: lib/src/module.dart [hunk 1]
```diff
@@ -252,6 +259,118 @@ abstract class Module {
...
+  ///
+  /// The default behavior of this function is to search through from all
+  /// inputs to all potential outputs.  If a [Module] implements custom behavior
+  /// internally (e.g. a custom gate or a cosimulated module), then it makes
+  /// sense to override this function to give an accurate picture.  If the
+  /// default behavior doesn't work (because no visible connectivity exists
+  /// inside the [Module]), then the return value will end up with all empty
+  /// [List]s in the values of the [Map].
+  ///
+  /// The result of this function is stored at [build] time.  The result is
```
Comment (mkorbel1) [inline lib/src/module.dart:332]: Update doc comment with changes about build-time

File: lib/src/module.dart [hunk 2]
```diff
@@ -252,6 +259,118 @@ abstract class Module {
...
+  /// primarily used for calculating valid and complete sensitivity lists
+  /// for [Combinational] execution.
+  @protected
+  Map<Logic, List<Logic>> getCombinationalPaths() {
```
Comment (mkorbel1) [inline lib/src/module.dart:336]: Reorder functions so get and getreverse are near each other
