### PR TITLE
[Issue-104] checks to prevent same conditional used multiple times

### LINKED ISSUE #104: Add checks to prevent the same `Conditional` from being used multiple times
## Motivation
If someone uses the same `Conditional` object multiple times in the same `_Always` or in different `_Always` blocks, it can cause unexpected behavior and simulation/synthesis mismatches.

## Desired solution
There should be an explicit check that `Conditional`s are not reused.  Perhaps a build-time check where each `Conditional` is assigned a parent `_Always`, and the `_Always` confirms there are no duplicates within itself?

### PR DESCRIPTION
**Pull request by quekyj**
## Description & Motivation

If someone uses the same Conditional object multiple times in the same _Always or in different _Always blocks, it can cause unexpected behavior and simulation/synthesis mismatches.

## Related Issue(s)

Fix #104 

## Testing

Make sure an exception is thrown when conditionals are reuse.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible?  If yes, how so?

no

## Documentation

> Does the change require any updates to documentation?  If so, where?  Are they included?

no

### CODE REVIEW

File: test/conditionals_test.dart [hunk 1]
```diff
@@ -373,6 +392,97 @@ void main() {
...
     });
+
+    test('should return exception if a conditional is used multiple times.',
+        () async {
+      expect(
+          () => MultipleConditionalModule(Logic(), Logic()), throwsException);
+    });
+  });
+
+  test(
```
Comment (mkorbel1) [inline test/conditionals_test.dart:403]: Why are all these tests added with this PR?  Were they missing last PR?

**Review by mkorbel1 — COMMENTED** [review]
Looks good! Just one question

File: test/conditionals_test.dart (hunk 1 above)
Comment (quekyj) [reply test/conditionals_test.dart:403]: It is because of the merge conflict. Some spacing added. So, it treats it like a newly added line since I add the conditionals test on the middle.

Comment (mkorbel1) [reply test/conditionals_test.dart:403]: It looks like the conflict resolution actually added duplicates to all these tests?  You should remove these duplicates

**Review by mkorbel1 — CHANGES_REQUESTED** [review]

File: test/conditionals_test.dart (hunk 1 above)
Comment (quekyj) [reply test/conditionals_test.dart:403]: Removed duplicated code

**Review by mkorbel1 — APPROVED** [review]
Looks good!
