### PR TITLE
[Issue-281] port initialized with empty name

### LINKED ISSUE #281: Port can be initialized with empty name
### Describe the bug

Port of the Module can be initialized with empty name.

### To Reproduce

```dart
// system verilog generate: input logic ,
final signal1 = addInput('', unamedSignal); 

```

### Expected behavior

throw exception on empty string port initialization

### Actual behavior

The initialization passed and the generated system verilog contains errors.

### Additional: Dart SDK info

_No response_

### Additional: pubspec.yaml

_No response_

### Additional: Context

_No response_

### PR DESCRIPTION
**Pull request by quekyj**
## Description & Motivation

Port of the Module can be initialized with an empty name.

## Related Issue(s)

Fix #281 

## Testing

Added Logic name and definition name test

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

No

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

No

### CODE REVIEW

File: lib/src/module.dart [hunk 1]
```diff
@@ -142,6 +142,8 @@ abstract class Module {
     } else if (reserveDefinitionName &&
         !Sanitizer.isSanitary(definitionName!)) {
       throw InvalidReservedNameException();
+    } else if (definitionName == '') {
+      throw NullReservedNameException();
```
Comment (mkorbel1) [inline lib/src/module.dart:146]: Good catch on this same bug for `definitionName` in module, but what about `name`?

Comment (mkorbel1) [inline lib/src/module.dart:146]: Shouldn't this be thrown `reserveDefinitionName` is set to true?  If it's not, we should probably silently rename it to something safe like some auto-generated name?

File: lib/src/logic.dart [hunk 2]
```diff
@@ -432,7 +432,9 @@ class Logic {
   /// The default value for [width] is 1.  The [name] should be synthesizable
   /// to the desired output (e.g. SystemVerilog).
   Logic({String? name, int width = 1})
-      : name = name == null ? 's${_signalIdx++}' : Sanitizer.sanitizeSV(name),
+      : name = (name == null || name == '')
```
Comment (mkorbel1) [inline lib/src/logic.dart:435]: All the places where you're checking `== ''`, can we use `isEmpty` instead?

**Review by mkorbel1 — CHANGES_REQUESTED** [review]

**Comment by quekyj** [comment]
I am not sure why the test failed but worked on my localhost.

**Comment by chykon** [comment]
> I am not sure why the test failed but worked on my localhost.

As far as I understand, this issue should be fixed by [this commit](https://github.com/intel/rohd/pull/306/commits/a990ee336b9b23ae498a67b621762171d0688508) in [this PR](https://github.com/intel/rohd/pull/306).

**Comment by mkorbel1** [comment]
Yes that's right, sorry just merged #306 in.

File: lib/src/module.dart [hunk 3]
```diff
@@ -142,6 +142,8 @@ abstract class Module {
     } else if (reserveDefinitionName &&
         !Sanitizer.isSanitary(definitionName!)) {
       throw InvalidReservedNameException();
+    } else if (reserveDefinitionName && definitionName!.isEmpty) {
+      throw NullReservedNameException();
```
Comment (mkorbel1) [inline lib/src/module.dart:146]: I think this should be an exception for invalid, not null?  Also, can't this not get hit because the sanitizer will always catch it?

File: lib/src/module.dart (hunk 1 above)
Comment (mkorbel1) [reply lib/src/module.dart:146]: Why resolved?

**Review by mkorbel1 — CHANGES_REQUESTED** [review]

File: lib/src/module.dart (hunk 1 above)
Comment (quekyj) [reply lib/src/module.dart]: My bad, I thought name and definition share on `_nameValidation` function. I added `_nameValidation` to the name as well. It should have the same behaviour now.

File: lib/src/module.dart (hunk 3 above)
Comment (quekyj) [reply lib/src/module.dart]: Okay, I swap the priority now and create a new exception on empty string. Feel like better to separate the exception message to avoid confusion.

File: lib/src/module.dart [hunk 4]
```diff
@@ -139,6 +139,8 @@ abstract class Module {
       String? definitionName, bool reserveDefinitionName) {
```
Comment (mkorbel1) [inline lib/src/module.dart:139]: Probably want to rename these to `name` and `reserveName` since they could be used for `definitionName` or `name`?

File: test/logic_name_test.dart [hunk 5]
```diff
@@ -42,4 +42,20 @@ void main() {
...
+    final bus = Logic(name: '');
+    expect(bus.name, isNot(equals('')));
+  });
+
+  group('port name:', () {
+    test('GIVEN port name is empty string THEN expected to see exception',
+        () async {
+      expect(() async {
+        LogicTestModule('');
+      }, throwsA((dynamic e) => e is Exception));
```
Comment (mkorbel1) [inline test/logic_name_test.dart:58]: Why not the specific type of exception?

**Review by mkorbel1 — CHANGES_REQUESTED** [review]
Looking good, just minor things

**Review by mkorbel1 — CHANGES_REQUESTED** [review]
Very close, nice work!

**Review by mkorbel1 — APPROVED** [review]
Looks good!
